"""Stable public surface for Phase 7 Governed Web Search/Fetch."""

from .application import WebKnowledgeService
from .contracts import (
    PUBLIC_WEB_SOURCE_CLASS,
    WEB_CITATION_EVIDENCE_SCHEMA_VERSION,
    PersistedTurnWebCitationEvidence,
    SourceAuthorityClass,
    UrlRejectionReason,
    WebCitation,
    WebCitationUnavailable,
    WebContentTransformation,
    WebEvidence,
    WebEvidenceGovernanceMode,
    WebFetchFailureReason,
    WebSearchActivation,
    WebSearchAndFetchResult,
    WebSearchFeatureConfig,
    WebSearchQuery,
    WebSearchResultItem,
    WebSearchRun,
    build_turn_web_citation_evidence,
    classify_content_transformation,
    classify_source_authority,
)
from .domain import (
    MAX_WEB_EVIDENCE_INJECTION_CHARACTERS,
    TRUNCATION_NOTICE,
    GetAddrInfoResult,
    Resolver,
    budget_evidence_for_injection,
    default_resolver,
    extract_html_title,
    extract_readable_text,
)
from .ports import (
    FetchedContent,
    FetchRejected,
    WebCitationEvidenceStorePort,
    WebFetchProviderPort,
    WebSearchProviderPort,
)

__all__ = [
    "MAX_WEB_EVIDENCE_INJECTION_CHARACTERS",
    "PUBLIC_WEB_SOURCE_CLASS",
    "TRUNCATION_NOTICE",
    "WEB_CITATION_EVIDENCE_SCHEMA_VERSION",
    "FetchRejected",
    "FetchedContent",
    "GetAddrInfoResult",
    "PersistedTurnWebCitationEvidence",
    "Resolver",
    "SourceAuthorityClass",
    "UrlRejectionReason",
    "WebCitation",
    "WebCitationEvidenceStorePort",
    "WebCitationUnavailable",
    "WebContentTransformation",
    "WebEvidence",
    "WebEvidenceGovernanceMode",
    "WebFetchFailureReason",
    "WebFetchProviderPort",
    "WebKnowledgeService",
    "WebSearchActivation",
    "WebSearchAndFetchResult",
    "WebSearchFeatureConfig",
    "WebSearchProviderPort",
    "WebSearchQuery",
    "WebSearchResultItem",
    "WebSearchRun",
    "budget_evidence_for_injection",
    "build_turn_web_citation_evidence",
    "classify_content_transformation",
    "classify_source_authority",
    "default_resolver",
    "extract_html_title",
    "extract_readable_text",
]
