"""Public guardrail-governance domain contracts (Phase 5)."""

from .actions import (
    NOT_EXECUTABLE_ACTION_IDS,
    ActionId,
    ActionRegistryEntry,
    NotExecutedReason,
)
from .canonicalization import canonical_result_payload, guardrail_result_digest_sha512
from .context_source import (
    CONTEXT_SOURCE_CLASS_DOCUMENTATION_RAG_CITATION,
    CONTEXT_SOURCE_CLASS_DOCUMENTATION_RAG_LEGACY_FLAT,
    ContextSourceUnit,
)
from .identities import (
    GUARDRAIL_CONTEXT_SOURCE_POINT_ID,
    GUARDRAIL_INPUT_POINT_ID,
    GUARDRAIL_OUTPUT_CANDIDATE_POINT_ID,
    GUARDRAIL_STREAM_CANDIDATE_POINT_ID,
    IDENTIFIER_PATTERN,
    POINT_ID_PATTERN,
    STAGE_CONTEXT,
    STAGE_INPUT,
    STAGE_OUTPUT,
    STAGE_STREAM,
)
from .results import (
    ApprovalOutcome,
    ApprovalState,
    AuthorityDecision,
    AuthorityOutcome,
    DetectionOutcome,
    ExecutedAction,
    ExecutionState,
    GuardDetection,
    GuardrailResult,
    PolicyApplicability,
    PolicyDecision,
    RecommendedAction,
    Severity,
)
from .safety_model import (
    RawSafetyModelObservation,
    SafetyModelFailureKind,
    SafetyModelResponse,
    decode_safety_model_observation,
)
from .snapshots import (
    ActionRegistrySnapshot,
    AuthoritySnapshot,
    DetectorRegistrySnapshot,
    PolicySnapshot,
)
from .spans import TypedSpan, spans_are_verified
from .taxonomy import (
    CATEGORY_AUTHORITY_SPOOFING,
    CATEGORY_JAILBREAK,
    CATEGORY_PII,
    CATEGORY_PROMPT_INJECTION,
    CATEGORY_SECRET,
    CATEGORY_TOOL_ABUSE,
    CATEGORY_UNKNOWN_UNRESOLVED,
    CATEGORY_UNSAFE_CONTENT,
    CategoryRegistry,
    CategoryRegistryEntry,
    default_category_registry,
)

__all__ = [
    "CATEGORY_AUTHORITY_SPOOFING",
    "CATEGORY_JAILBREAK",
    "CATEGORY_PII",
    "CATEGORY_PROMPT_INJECTION",
    "CATEGORY_SECRET",
    "CATEGORY_TOOL_ABUSE",
    "CATEGORY_UNKNOWN_UNRESOLVED",
    "CATEGORY_UNSAFE_CONTENT",
    "CONTEXT_SOURCE_CLASS_DOCUMENTATION_RAG_CITATION",
    "CONTEXT_SOURCE_CLASS_DOCUMENTATION_RAG_LEGACY_FLAT",
    "GUARDRAIL_CONTEXT_SOURCE_POINT_ID",
    "GUARDRAIL_INPUT_POINT_ID",
    "GUARDRAIL_OUTPUT_CANDIDATE_POINT_ID",
    "GUARDRAIL_STREAM_CANDIDATE_POINT_ID",
    "IDENTIFIER_PATTERN",
    "NOT_EXECUTABLE_ACTION_IDS",
    "POINT_ID_PATTERN",
    "STAGE_CONTEXT",
    "STAGE_INPUT",
    "STAGE_OUTPUT",
    "STAGE_STREAM",
    "ActionId",
    "ActionRegistryEntry",
    "ActionRegistrySnapshot",
    "ApprovalOutcome",
    "ApprovalState",
    "AuthorityDecision",
    "AuthorityOutcome",
    "AuthoritySnapshot",
    "CategoryRegistry",
    "CategoryRegistryEntry",
    "ContextSourceUnit",
    "DetectionOutcome",
    "DetectorRegistrySnapshot",
    "ExecutedAction",
    "ExecutionState",
    "GuardDetection",
    "GuardrailResult",
    "NotExecutedReason",
    "PolicyApplicability",
    "PolicyDecision",
    "PolicySnapshot",
    "RawSafetyModelObservation",
    "RecommendedAction",
    "SafetyModelFailureKind",
    "SafetyModelResponse",
    "Severity",
    "TypedSpan",
    "canonical_result_payload",
    "decode_safety_model_observation",
    "default_category_registry",
    "guardrail_result_digest_sha512",
    "spans_are_verified",
]
