"""Stable public surface for the documentation RAG module."""

from .application import DocumentationRagApplicationService
from .contracts import (
    CITATION_EVIDENCE_SCHEMA_VERSION,
    CitationUnavailable,
    CorpusManifest,
    DocumentationAugmentation,
    DocumentationCitation,
    DocumentationGroundingState,
    DocumentationRagAvailability,
    DocumentationRagMode,
    DocumentationRagRequestContext,
    DocumentationRetrievalState,
    DocumentationWarning,
    DocumentManifestEntry,
    LocalDocumentationRagFeatureConfig,
    PersistedTurnCitationEvidence,
    build_turn_citation_evidence,
)
from .ports import (
    ChunkerPort,
    CitationEvidenceStorePort,
    CitationPort,
    ContextAssemblerPort,
    ContextualRagOrchestratorPort,
    DocumentSourcePort,
    EmbeddingPort,
    IndexStorePort,
    RagOrchestratorPort,
    RetrieverPort,
)

__all__ = [
    "CITATION_EVIDENCE_SCHEMA_VERSION",
    "ChunkerPort",
    "CitationEvidenceStorePort",
    "CitationPort",
    "CitationUnavailable",
    "ContextAssemblerPort",
    "ContextualRagOrchestratorPort",
    "CorpusManifest",
    "DocumentManifestEntry",
    "DocumentSourcePort",
    "DocumentationAugmentation",
    "DocumentationCitation",
    "DocumentationGroundingState",
    "DocumentationRagApplicationService",
    "DocumentationRagAvailability",
    "DocumentationRagMode",
    "DocumentationRagRequestContext",
    "DocumentationRetrievalState",
    "DocumentationWarning",
    "EmbeddingPort",
    "IndexStorePort",
    "LocalDocumentationRagFeatureConfig",
    "PersistedTurnCitationEvidence",
    "RagOrchestratorPort",
    "RetrieverPort",
    "build_turn_citation_evidence",
]
