"""Framework-independent Context Compaction domain: identity, measurement, budget, artifacts."""

from .artifacts import (
    TERMINAL_ATTEMPT_STATES,
    ActivationRecord,
    ActivationResult,
    ActiveContextProjection,
    CompactionAttempt,
    CompactionAttemptState,
    CompactionPlan,
    CompactionStrategy,
    ContextHandoffArtifact,
    ContextSourceReference,
    ContextSourceTurnReference,
    OmittedRange,
    PreActionSnapshot,
    RecentVerbatimTurn,
    RecoveryIndex,
    RecoveryIndexEntry,
    RehydratedTurn,
    RehydrationFailure,
    RehydrationFailureCode,
    SelectiveRehydrationRequest,
    SelectiveRehydrationResult,
    StructuredContextArtifact,
    StructuredContextSections,
    validate_attempt_transition,
)
from .budget import (
    ContextBudgetSnapshot,
    PressureState,
    ThresholdConfig,
    compute_effective_remaining_budget,
    compute_pressure_state,
    generation_should_be_blocked,
)
from .errors import ContextCompactionDomainError, ContextCompactionDomainErrorCode
from .identity import (
    DEFAULT_BRANCH_ID,
    CompactionAttemptId,
    CompactionPlanId,
    ContextActionId,
    ContextBranchId,
    HandoffArtifactId,
    RecoveryIndexId,
    SnapshotId,
    StructuredContextId,
)
from .measurement import MeasuredTokens, MeasurementClass

__all__ = [
    "DEFAULT_BRANCH_ID",
    "TERMINAL_ATTEMPT_STATES",
    "ActivationRecord",
    "ActivationResult",
    "ActiveContextProjection",
    "CompactionAttempt",
    "CompactionAttemptId",
    "CompactionAttemptState",
    "CompactionPlan",
    "CompactionPlanId",
    "CompactionStrategy",
    "ContextActionId",
    "ContextBranchId",
    "ContextBudgetSnapshot",
    "ContextCompactionDomainError",
    "ContextCompactionDomainErrorCode",
    "ContextHandoffArtifact",
    "ContextSourceReference",
    "ContextSourceTurnReference",
    "HandoffArtifactId",
    "MeasuredTokens",
    "MeasurementClass",
    "OmittedRange",
    "PreActionSnapshot",
    "PressureState",
    "RecentVerbatimTurn",
    "RecoveryIndex",
    "RecoveryIndexEntry",
    "RecoveryIndexId",
    "RehydratedTurn",
    "RehydrationFailure",
    "RehydrationFailureCode",
    "SelectiveRehydrationRequest",
    "SelectiveRehydrationResult",
    "SnapshotId",
    "StructuredContextArtifact",
    "StructuredContextId",
    "StructuredContextSections",
    "ThresholdConfig",
    "compute_effective_remaining_budget",
    "compute_pressure_state",
    "generation_should_be_blocked",
    "validate_attempt_transition",
]
