"""Public persistent conversation domain contracts."""

from .errors import (
    ConversationDomainError,
    ConversationDomainErrorCode,
    ConversationStorageError,
    ConversationStorageErrorCode,
    StorageMutationOutcome,
)
from .identity import (
    ConversationId,
    ConversationMessageId,
    ConversationOperationId,
    ConversationScopeId,
    ConversationSessionId,
    ConversationTurnId,
)
from .models import (
    MAX_CONVERSATION_TITLE_CHARACTERS,
    MAX_PERSISTED_MESSAGE_CHARACTERS,
    ConversationSessionRecord,
    ConversationSessionState,
    ConversationSnapshot,
    ConversationState,
    ConversationSummary,
    ConversationTurn,
    ConversationTurnOrigin,
    ConversationTurnState,
    PersistedConversationMessage,
    PersistedConversationRole,
    project_generation_history,
    transition_conversation_state,
    transition_session,
    transition_turn,
)

__all__ = [
    "MAX_CONVERSATION_TITLE_CHARACTERS",
    "MAX_PERSISTED_MESSAGE_CHARACTERS",
    "ConversationDomainError",
    "ConversationDomainErrorCode",
    "ConversationId",
    "ConversationMessageId",
    "ConversationOperationId",
    "ConversationScopeId",
    "ConversationSessionId",
    "ConversationSessionRecord",
    "ConversationSessionState",
    "ConversationSnapshot",
    "ConversationState",
    "ConversationStorageError",
    "ConversationStorageErrorCode",
    "ConversationSummary",
    "ConversationTurn",
    "ConversationTurnId",
    "ConversationTurnOrigin",
    "ConversationTurnState",
    "PersistedConversationMessage",
    "PersistedConversationRole",
    "StorageMutationOutcome",
    "project_generation_history",
    "transition_conversation_state",
    "transition_session",
    "transition_turn",
]
