"""Public governance-definitions domain contracts."""

from .compiler import (
    CompiledPlan,
    CompilerInput,
    DigestedCompiledPlan,
    GovernanceProfile,
    SelectedSectionRef,
    compile_plan,
    digest_plan,
    plan_cache_key,
    plan_digest_sha512,
    plan_matches_requested_digests,
    plan_payload_for_digest,
    verify_digested_plan,
)
from .errors import GovernanceDefinitionError, GovernanceDefinitionErrorCode
from .manifest import (
    DefinitionEntry,
    PackageManifest,
    SignedPackageManifest,
    SourceEntry,
    manifest_digest_sha512,
    manifest_payload_for_digest,
    sign_manifest,
    verify_signed_manifest,
)
from .mode import (
    PHASE_3_MODE_DESCRIPTORS,
    GovernanceMode,
    GovernanceModeAvailability,
    GovernanceModeDescriptor,
    GovernanceModeSnapshot,
    GovernanceModeTransitionError,
    build_governance_mode_snapshot,
    governance_mode_digest,
    request_mode_transition,
)
from .normalized_ir import (
    DigestedNormalizedGovernanceDefinition,
    IrIdentity,
    IrSection,
    IrSourceProvenance,
    NormalizedGovernanceDefinition,
    digest_ir,
    ir_digest_sha512,
    ir_payload_for_digest,
    verify_digested_ir,
)
from .repository_policy import (
    KNOWN_SCHEMA_IDS,
    resolve_definition_states,
    resolve_package_state,
)
from .source_verification import SourceVerification
from .states import DefinitionState, PackageState, ProviderState, SourceState

__all__ = [
    "KNOWN_SCHEMA_IDS",
    "PHASE_3_MODE_DESCRIPTORS",
    "CompiledPlan",
    "CompilerInput",
    "DefinitionEntry",
    "DefinitionState",
    "DigestedCompiledPlan",
    "DigestedNormalizedGovernanceDefinition",
    "GovernanceDefinitionError",
    "GovernanceDefinitionErrorCode",
    "GovernanceMode",
    "GovernanceModeAvailability",
    "GovernanceModeDescriptor",
    "GovernanceModeSnapshot",
    "GovernanceModeTransitionError",
    "GovernanceProfile",
    "IrIdentity",
    "IrSection",
    "IrSourceProvenance",
    "NormalizedGovernanceDefinition",
    "PackageManifest",
    "PackageState",
    "ProviderState",
    "SelectedSectionRef",
    "SignedPackageManifest",
    "SourceEntry",
    "SourceState",
    "SourceVerification",
    "build_governance_mode_snapshot",
    "compile_plan",
    "digest_ir",
    "digest_plan",
    "governance_mode_digest",
    "ir_digest_sha512",
    "ir_payload_for_digest",
    "manifest_digest_sha512",
    "manifest_payload_for_digest",
    "plan_cache_key",
    "plan_digest_sha512",
    "plan_matches_requested_digests",
    "plan_payload_for_digest",
    "request_mode_transition",
    "resolve_definition_states",
    "resolve_package_state",
    "sign_manifest",
    "verify_digested_ir",
    "verify_digested_plan",
    "verify_signed_manifest",
]
